kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - ServiceRef:
       name: nginx