apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::124355635734:role/eksctl-expense-addon-iamserviceaccount-kube-s-Role1-ta9wRvskc0YP
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::124355635734:user/bhavya
      username: bhavya
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-18T12:38:43Z"
  name: aws-auth
  namespace: kube-system